main/urls.py
from django.contrib import admin
from django.urls import path,include
from stands.views import index,reserva_criar,reserva_editar,reserva_remover,reserva

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('reserva/<int:id>/',reserva,name='reserva'),
    path('reserva/',reserva_criar,name='reserva_criar'),
    path('reserva/editar/<int:id>/',reserva_editar, name='reserva_editar'),
    path('reserva/remover/<int:id>/',reserva_remover,name='reserva_remover'),
    path('accounts/', include('django.contrib.auth.urls')),
]

stands/models.py
from django.db import models

# Create your models here.

class Stand(models.Model):
    localizacao = models.CharField(max_length=100)
    valor = models.FloatField()

    def __str__(self):
        return self.localizacao


class Reserva(models.Model):
    cnpj = models.CharField(max_length=14)
    nome_empresa = models.CharField(max_length=150)
    categoria = models.CharField(max_length=100)
    quitado = models.BooleanField()
    stand = models.OneToOneField(Stand,on_delete=models.CASCADE, null=True)
    data = models.DateField(auto_now_add=True)

    

stands/forms.py
from django.forms import ModelForm
from django import forms
from .models import Reserva

class ReservaForm(ModelForm):

    class Meta:
        model = Reserva
        fields = '__all__'
        widgets = {
            'cnpj' : forms.TextInput(attrs={'class': 'form-control' }),
            'nome_empresa' : forms.TextInput(attrs={'class': 'form-control' }),
            'categoria' : forms.TextInput(attrs={'class': 'form-control' }),
            'quitado' : forms.CheckboxInput(attrs={'class': 'form-check-input','type':'checkbox'}),  
            'stand' : forms.Select(attrs={'class': 'form-contrl'}),
        }

stands/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Reserva
from .forms import ReservaForm
from .filters import ReservaFilter
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    reserva = Reserva.objects.all().order_by('data')
    filter = ReservaFilter(request.GET, queryset=Reserva.objects.all())
    paginator = Paginator(reserva, 5)
    page = request.GET.get('page')
    pag_obj = paginator.get_page(page)
    context = {
        'reserva' : reserva, 'filter' : filter, 'pag_obj' : pag_obj
    }
    return render(request, 'reserva/index.html',context)

@login_required
def reserva_editar(request,id):
    reserva = get_object_or_404(Reserva,id=id)  
   
    if request.method == 'POST':
        form = ReservaForm(request.POST,request.FILES,instance=reserva)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ReservaForm(instance=reserva)

    return render(request,'reserva/form_reserva.html',{'form':form})

@login_required
def reserva_remover(request, id):
    reserva = get_object_or_404(Reserva, id=id)
    reserva.delete()
    return redirect('index') 

@login_required
def reserva_criar(request):
    if request.method == 'POST':
        form = ReservaForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            form = ReservaForm()
            return redirect('index')
    else:
        form = ReservaForm()

    return render(request, "reserva/form_reserva.html", {'form': form})

@login_required
def reserva(request, id):
    reserva = get_object_or_404(Reserva,id=id)
    if reserva.quitado == True:
        reserva.quitado = 'Sim'
    else:
        reserva.quitado = 'Não'
    context ={
        'reserva':reserva
    }
    return render(request, "reserva/reserva.html",context)

stands/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">FINECAP</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Início</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'reserva_criar' %}">Nova Reserva</a>
          </li>
        </ul>
          <a class="navbar-text" href="{% url 'logout' %}" style="text-decoration: none;">Sair</a>
      </div>
    </div>
  </nav>
    <main style="margin-left:60px; margin-right:60px; margin-top: 30px;">  
    {% block content %}

    {% endblock %}
    </main> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

stands/templates/reserva/form_reserva.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="nome" class="form-label">CNPJ</label>
        {{ form.cnpj }}       
    </div>
    
    <div class="mb-3">
        <label for="nome" class="form-label">Nome da Empresa</label>
        {{ form.nome_empresa }}
    </div>

    <div class="mb-3">
        <label for="id_categoria" class="form-label">Categoria</label>
        {{ form.categoria }}
    </div>
    
    <div class="mb-3">
        <label for="id_quitado" class="form-check-label">Quitado</label>
        {{ form.quitado }} 
    </div>

    <div class="mb-3">
        <label for="nome" class="form label">Stand</label>
        {{ form.stand }}
    </div>

    <div class="mb-3">               
        <button type="submit" class="btn btn-primary">Reservar</button>
    </div>
</form> 
{%endblock%}

stands/templates/reserva/index.html
{% extends 'base.html' %}
{% block content %}

    <form class="d-flex" style="justify-content: space-between; width: 80%; align-items: center;" method="get">
        {{ filter.form.as_p }}
      <input type="submit" class="btn btn-primary"/>
    </form>
    {% for i in pag_obj %}
        <div class="card" style="margin-bottom: 30px;">
          <div class="card-body">
            <h5 class="card-title">{{ i.nome_empresa }}</h5>
            <p class="card-text">{{ i.categoria }}</p>
            <p class="card-text">{{ i.stand }}</p>
            <p class="card-text">{{ i.data }}</p>
            <a href="{% url 'reserva' i.id %}" class="btn btn-primary">Detalhar</a>
            <a href="{% url 'reserva_editar' i.id %}" class="btn btn-primary">Editar</a>
            <a href="{% url 'reserva_remover' i.id %}" class="btn btn-danger">Remover</a>
          </div>
        </div>
    {% endfor %}

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if pag_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ pag_obj.1 }}">Primeira</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ pag_obj.previous_page_number }}">Anterior</a></li>        
        {% endif %}
            
        <li class="page-item"><a class="page-link" href="?page={{ pag_obj.number }}">{{ pag_obj.number }} de {{ pag_obj.paginator.num_pages }}</a></li>
 
        {% if pag_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ pag_obj.next_page_number }}">Próxima</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ pag_obj.paginator.num_pages }}">Última </a></li>          
        {% endif %}

        <span class="current">
          
        </span>
      </ul>
    </nav>
              
  </div>

    <!-- {% for i in reserva %}
      <div class="card" style="margin-bottom: 30px;">
        <div class="card-body">
          <h5 class="card-title">{{ i.nome_empresa }}</h5>
          <p class="card-text">{{ i.categoria }}</p>
          <p class="card-text">{{ i.stand }}</p>
          <p class="card-text">{{ i.data }}</p>
          <a href="{% url 'reserva' i.id %}" class="btn btn-primary">Detalhar</a>
          <a href="{% url 'reserva_editar' i.id %}" class="btn btn-primary">Editar</a>
          <a href="{% url 'reserva_remover' i.id %}" class="btn btn-danger">Remover</a>
        </div>
      </div>    
    {% endfor %} -->
{%endblock%}

stands/templates/reserva/reserva.html
{% extends 'base.html' %}
{% block content %}
    <div class="card" style="width: 50rem;" f>
        <div class="card-body">

        <h5 class="card-title" style="font-size: 5rem;">{{ reserva.nome_empresa }}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary" style="font-size: 2rem;">CNPJ: {{ reserva.cnpj }}</h6>
        
        <h6 class="card-text" style="font-size: 2rem; margin-top: 3rem;">Categoria</h6>
        <p class="card-text" style="font-size: 2rem; margin-bottom: 2rem;">{{ reserva.categoria }}</p>
        
        <h6 class="card-text" style="font-size: 2rem;">Localização do stand</h6>
        <p class="card-text" style="font-size: 2rem; margin-bottom: 2rem;">{{ reserva.stand }}</p>
        
        <h6 class="card-text" style="font-size: 2rem;">Quitado</h6>
        <p class="card-text" style="font-size: 2rem; margin-bottom: 2rem;">{{ reserva.quitado }}</p>
          
        <h6 class="card-text" style="font-size: 2rem;">Valor</h6>
        <p class="card-text" style="font-size: 2rem; margin-bottom: 2rem;">{{ reserva.stand.valor }}</p>

        <h6 class="card-text" style="font-size: 2rem;">Data da reserva</h6>
        <p class="card-text" style="font-size: 2rem; margin-bottom: 2rem;">{{ reserva.data }}</p>

    </div>
    </div>
{% endblock %}